apiVersion: v1
kind: Service
metadata:
  name: coworking-space-api
spec:
  selector:
    app.kubernetes.io/name: coworking-space-api
  ports:
  - name: "5153"
    protocol: TCP
    port: 5153
    targetPort: 5153
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coworking-space-api
  labels:
    name: coworking-space-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: coworking-space-api
  template:
    metadata:
      labels:
        service: coworking-space-api
    spec:
      containers:
      - name: coworking-space-api
        image: 099331234388.dkr.ecr.us-east-1.amazonaws.com/udacity-ecr:15
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5153
          initialDelaySeconds: 10
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5153
          initialDelaySeconds: 10
          timeoutSeconds: 10
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
